name: Publish SDK to NuGet

on:
  push:
    tags:
      - "v*" # Triggers the workflow when a new tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git for GitVersion
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Run GitVersion
        env:
          GITVERSION_SECRET: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet-gitversion /output buildserver

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build OriginalSDK/OriginalSDK.csproj --configuration Release

      - name: Pack the project
        run: dotnet pack OriginalSDK/OriginalSDK.csproj --configuration Release --output ./nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "nupkg/OriginalSDK.*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
