name: Publish SDK to NuGet

on:
  push:
    tags:
      - "v*" # Triggers the workflow when a new tag is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build OriginalSDK --configuration Release /p:Version=${VERSION}

      - name: Pack
        run: dotnet pack OriginalSDK --configuration Release /p:Version=${VERSION} --output nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "nupkg/OriginalSDK.${VERSION}.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
