name: Build SDK and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Restore dependencies
        run: dotnet restore OriginalSDK.sln

      - name: Build the solution
        run: dotnet build OriginalSDK.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test OriginalSDK.sln --verbosity normal
